### ISSUE TITLE
Re-export Positive or define Num

### ISSUE THREAD

**Issue by gromakovsky** [serokell/servant-util#18]
In order to construct `PaginationSpec` I need to provide a `Positive Natural` value if I use `PaginationSpec` constructor or `itemsOnPage`. `Positive` is defined in a module with `Internal` in its name and apparently I am forced to import it and I feel awkward when I do it. Forcing users to import _internal_ modules to use _external_ functionality sounds bad.

An alternative is to define `Num a => Num (Positive a)` instance.

**Comment by Martoon-00** [comment]
Fair, the situation looks quite wrong. I created a PR.
