### ISSUE TITLE
Document how to use `NullsSortingOrder`

### ISSUE THREAD

**Issue by gromakovsky** [serokell/servant-util#21]
There is `NullsSortingOrder` which specifies "where to place null fields". But in `Servant.Util.Combinators.Sorting.Construction` I don't see any way to specify this order and in general from docs it's not clear how to pass it in query for example.

**Comment by Martoon-00** [comment]
At the moment, there are only hints for this feature, it is not implemented yet :unamused: 

You are very welcome to contribute :nate: (I can provide any suitable guidance). It's worth starting by uncommenting the code marked with `TODO [DSCP-425]`.

**Comment by Martoon-00** [comment]
Closing in favor of #28.
