### ISSUE TITLE
Why isn't IsAutoFilter a subclass of Functor?

### ISSUE THREAD

**Issue by treeowl** [serokell/servant-util#39]
`IsAutoFilter` includes a method `mapAutoFilterValue :: (a -> b) -> filter a -> filter b`.  This method is not documented. Is it expected to obey the functor laws? If so, why not drop it and add a `Functor filter` superclass? If not, how is it expected to behave?

**Comment by Martoon-00** [comment]
I can't come with a sensible example when it would be necessary.

Thinking about it now, probably having extra `mapAutoFliterValue` is really not worth it, let's replace with `Functor` superclass.
