### ISSUE TITLE
Export the `MkSomeFilter` typeclass

### ISSUE THREAD

**Issue by skykanin** [serokell/servant-util#43]
`servant-util` should export the `MkSomeFilter` typeclass from the [Servant.Util.Combinators.Filtering.Construction](https://github.com/serokell/servant-util/blob/290f0e6db5204ca64f54374a06bdc98cfbf4cda2/servant-util/src/Servant/Util/Combinators/Filtering/Construction.hs#L93) module so that library consumers can implement their own helpers for defining manual filters and give them a type signature.

**Comment by Martoon-00** [comment]
That's a fair concern, thanks for pointing it out.

Created #44, please review it.
